// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVrO7lx0qMcrVHYA3GIMMbdCZ0gC1Hwro',
    appId: '1:197482749995:web:49f0938697af0f62154a6e',
    messagingSenderId: '197482749995',
    projectId: 'test-login-32ada',
    authDomain: 'test-login-32ada.firebaseapp.com',
    storageBucket: 'test-login-32ada.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsX6o_nIGY4YjZWegFc0FPfRakKQhA0s',
    appId: '1:197482749995:android:6bd180859b2204e8154a6e',
    messagingSenderId: '197482749995',
    projectId: 'test-login-32ada',
    storageBucket: 'test-login-32ada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMk9EHvNuoX1Vuz-SNi2LwgNXvjqRZTj0',
    appId: '1:197482749995:ios:92b6880dcaced876154a6e',
    messagingSenderId: '197482749995',
    projectId: 'test-login-32ada',
    storageBucket: 'test-login-32ada.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMk9EHvNuoX1Vuz-SNi2LwgNXvjqRZTj0',
    appId: '1:197482749995:ios:92b6880dcaced876154a6e',
    messagingSenderId: '197482749995',
    projectId: 'test-login-32ada',
    storageBucket: 'test-login-32ada.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVrO7lx0qMcrVHYA3GIMMbdCZ0gC1Hwro',
    appId: '1:197482749995:web:5faa9303dfff9037154a6e',
    messagingSenderId: '197482749995',
    projectId: 'test-login-32ada',
    authDomain: 'test-login-32ada.firebaseapp.com',
    storageBucket: 'test-login-32ada.firebasestorage.app',
  );
}
